FROM node:18-alpine

WORKDIR /app

# Копирование package.json
COPY package.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY . .

# Создание пользователя для безопасности
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app
USER nextjs

# Команда по умолчанию
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
